// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Midterm_Project.Data;

#nullable disable

namespace Midterm_Project.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Midterm_Project.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 4, 9, 9, 15, 31, 434, DateTimeKind.Utc).AddTicks(9922),
                            Description = "Electronic devices",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 4, 9, 9, 15, 31, 434, DateTimeKind.Utc).AddTicks(9924),
                            Description = "Clothing items",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 4, 9, 9, 15, 31, 434, DateTimeKind.Utc).AddTicks(9926),
                            Description = "Books and literature",
                            Name = "Books"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 4, 9, 9, 15, 31, 434, DateTimeKind.Utc).AddTicks(9927),
                            Description = "Household appliances",
                            Name = "Home Appliances"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 4, 9, 9, 15, 31, 434, DateTimeKind.Utc).AddTicks(9929),
                            Description = "Furniture items",
                            Name = "Furniture"
                        });
                });

            modelBuilder.Entity("Midterm_Project.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 4, 9, 9, 15, 31, 435, DateTimeKind.Utc).AddTicks(134),
                            Description = "Latest smartphone model",
                            Name = "Smartphone",
                            Price = 499.99m,
                            StockQuantity = 100,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 4, 9, 9, 15, 31, 435, DateTimeKind.Utc).AddTicks(137),
                            Description = "Cotton T-Shirt",
                            Name = "T-Shirt",
                            Price = 19.99m,
                            StockQuantity = 200,
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 4, 9, 9, 15, 31, 435, DateTimeKind.Utc).AddTicks(138),
                            Description = "Best-selling novel",
                            Name = "Novel",
                            Price = 9.99m,
                            StockQuantity = 50,
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 4, 9, 9, 15, 31, 435, DateTimeKind.Utc).AddTicks(141),
                            Description = "Large capacity refrigerator",
                            Name = "Refrigerator",
                            Price = 799.99m,
                            StockQuantity = 20,
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 4, 9, 9, 15, 31, 435, DateTimeKind.Utc).AddTicks(144),
                            Description = "Comfortable sofa set",
                            Name = "Sofa",
                            Price = 899.99m,
                            StockQuantity = 10,
                            SupplierId = 5
                        });
                });

            modelBuilder.Entity("Midterm_Project.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            ContactPerson = "John Doe",
                            Email = "john@example.com",
                            Name = "ABC Electronics",
                            Phone = "123456789"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Elm St",
                            ContactPerson = "Jane Smith",
                            Email = "jane@example.com",
                            Name = "XYZ Clothing",
                            Phone = "987654321"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Oak St",
                            ContactPerson = "Alice Johnson",
                            Email = "alice@example.com",
                            Name = "Book World",
                            Phone = "456123789"
                        },
                        new
                        {
                            Id = 4,
                            Address = "987 Pine St",
                            ContactPerson = "Michael Brown",
                            Email = "michael@example.com",
                            Name = "Home Comfort Appliances",
                            Phone = "654987321"
                        },
                        new
                        {
                            Id = 5,
                            Address = "654 Cedar St",
                            ContactPerson = "Emily White",
                            Email = "emily@example.com",
                            Name = "Furniture Palace",
                            Phone = "321789654"
                        });
                });

            modelBuilder.Entity("Midterm_Project.Models.Product", b =>
                {
                    b.HasOne("Midterm_Project.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Midterm_Project.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Midterm_Project.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Midterm_Project.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
